name: Build/release

on:
  push:
    branches: [master]
    tags:
      # Build on every tag in the form v1.2.3-something.4
      - "v*"
  pull_request:
    branches: [master]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Set environment variable USE_HARD_LINKS
        run: echo "USE_HARD_LINKS=false" >> $GITHUB_ENV
      - name: Build/release Electron app
        run: |
          npm i yarn -g
          yarn
          yarn prerelease
          yarn release
      - name: upload exe
        uses: actions/upload-artifact@master
        with:
          name: windows
          path: build/
